version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-orderservice
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: orderservice_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - laravel-net

volumes:
  postgres_data:

networks:
  laravel-net:
    external: true
