services:
  product_app:
    build: .
    container_name: product-service-app
    volumes:
      - ../productservice:/var/www
    networks:
      - laravel-net
    depends_on:
      product_db:
        condition: service_healthy

  product_web:
    image: nginx:stable-alpine
    container_name: product-service-nginx
    ports:
      - "8002:80"
    volumes:
      - ../productservice:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel-net
    depends_on:
      - product_app

  product_db:
    image: mysql:8
    container_name: product-service-db
    environment:
      MYSQL_DATABASE: product_service_db
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - product_db_data:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - laravel-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  phpmyadmin_product:
    image: phpmyadmin/phpmyadmin
    container_name: product-service-phpmyadmin
    restart: always
    ports:
        - "8082:80"  # 👉 akses phpMyAdmin di http://localhost:8082
    environment:
      PMA_HOST: product_db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: rootpassword
    depends_on:
        - product_db
    networks:
        - laravel-net


networks:
  laravel-net:
    external: true

volumes:
  product_db_data: