# version: '3.8'
# services:
#   user-app:
#     build: .
#     container_name: user_service
#     ports:
#       - "8001:80"
#     # environment:
#     #   - RABBITMQ_HOST=rabbitmq
#     networks:
#       - micro_net
#     volumes:
#       - ./app:/var/www

# networks:
#   micro_net:
#     external: true


services:
  user_app:
    build: .
    container_name: user-service-app
    volumes:
      - ../userservice:/var/www
    networks:
      - laravel-net
    depends_on:
      user_db:
        condition: service_healthy

  user_web:
    image: nginx:stable-alpine
    container_name: user-service-nginx
    ports:
      - "8001:80"
    volumes:
      - ../userservice:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel-net
    depends_on:
      - user_app

  user_db:
    image: mysql:8
    container_name: user-service-db
    environment:
      MYSQL_DATABASE: userservice_db
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - user_db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - laravel-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  laravel-net:
    external: true

volumes:
  user_db_data:
