
services:
  user_app:
    build: .
    container_name: user-service-app
    volumes:
      - ../userservice:/var/www
    networks:
      - laravel-net
    depends_on:
      user_db:
        condition: service_healthy

  user_web:
    image: nginx:stable-alpine
    container_name: user-service-nginx
    ports:
      - "8001:80"
    volumes:
      - ../userservice:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel-net
    depends_on:
      - user_app

  user_db:
    image: mysql:8
    container_name: user-service-db
    environment:
      MYSQL_DATABASE: userservice_db
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - user_db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - laravel-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5


  phpmyadmin_user:
    image: phpmyadmin/phpmyadmin
    container_name: user-service-phpmyadmin
    restart: always
    ports:
      - "8081:80"  # ⬅️ Bisa diakses di http://localhost:8081
    environment:
      PMA_HOST: user_db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: rootpassword
    depends_on:
      - user_db
    networks:
      - laravel-net

networks:
  laravel-net:
    external: true

volumes:
  user_db_data:
